version: '3.8'

services:
  django:
    container_name: e-commerce-django
    build:  .
    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - .:/E-commerce
    env_file:
      - ./.env.dev
    depends_on:
      - postgres
      - redis
  
  postgres:
    image: postgres:15
    container_name: e-commerce-postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev.postgres
  
  redis:
    image: "redis:alpine"
    container_name: e-commerce-redis

  celery:
    container_name: e-commerce-celery
    build: .
    command: celery -A django_ecommerce worker -l INFO
    volumes:
      - .:/E-commerce
    env_file:
      - ./.env.dev
      - ./.env.dev.postgres
    depends_on:   
      - postgres
      - redis
  
  flower:
    container_name: e-commerce-flower
    build: .
    command: celery -A django_ecommerce flower 
    ports:
      - 5555:5555
    volumes:
      - .:/E-commerce
    env_file:
      - ./.env.dev
    depends_on:   
      - redis

volumes:
  postgres_data: