version: '3.8'

services:
  django:
    build:  .
    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - .:/E-commerce
    env_file:
      - ./.env.dev
    depends_on:
      - postgres
  
  postgres:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=django_ecommerce
      - POSTGRES_PASSWORD=django_ecommerce
      - POSTGRES_DB=django_ecommerce_dev

volumes:
  postgres_data: