# Generated by Django 4.2.9 on 2024-01-26 18:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_customuser_is_verified_otp"),
    ]

    operations = [
        migrations.AddField(
            model_name="otp",
            name="expiry_timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 1, 27, 18, 49, 8, 755907, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
