# Generated by Django 4.2.9 on 2024-01-27 01:54

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_otp_expiry_timestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otp",
            name="expiry_timestamp",
            field=models.DateTimeField(
                default=accounts.models.expiration, verbose_name="Expire on"
            ),
        ),
    ]
