# Generated by Django 4.2.9 on 2024-02-08 00:08

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_otp_expiry_timestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="full_name",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=13, region=None
            ),
        ),
    ]
